language: c
sudo: false
addons:
    apt:
        packages:
            - libgmp-dev
notifications:
    email:
        recipients:
            - travisci@benary.org
        on_success: change
        on_failure: always
cache:
    directories:
        - $HOME/.stack

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
    - stack --no-terminal --skip-ghc-check setup
    - stack build --no-terminal --skip-ghc-check --only-snapshot
script:
    - stack --no-terminal --skip-ghc-check test

